services:
  - type: web
    name: autonote
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: autonote-disk
      mountPath: /opt/render/project/src
      sizeGB: 10 